### ISSUE TITLE
AC66U only able to see 87U images

### ISSUE THREAD

**Issue by tirthob** [tuapuikia/asuswrt-phantom#1]
Please let me know where I can download phantom for AC66U thanks

only see these builds made 
Index of /firmware/

../
RT-AC68U_378.56_phantom-81ed8c2.zip                15-Oct-2015 12:39            31956077
RT-AC87U_378.55_phantom-947ab66.zip                13-Jul-2015 10:21            43790406
RT-AC87U_378.56_phantom-10f80e4.zip                07-Oct-2015 11:11            46104104
RT-AC87U_378.56_phantom-2821e2c.zip                12-Oct-2015 18:04            46103865
RT-AC87U_378.56_phantom-295b296.zip                08-Oct-2015 16:25            46103088
RT-AC87U_378.56_phantom-4203178.zip                12-Oct-2015 10:55            46104238
RT-AC87U_378.56_phantom-4ead97f.zip                30-Oct-2015 11:59            46108026
RT-AC87U_378.56_phantom-4f26db8.zip                03-Sep-2015 12:04            46224354
RT-AC87U_378.56_phantom-70d2f7e.zip                13-Oct-2015 16:20            46104570
RT-AC87U_378.56_phantom-816c9d3.zip                20-Oct-2015 12:31            46103898
RT-AC87U_378.56_phantom-81ed8c2.zip                15-Oct-2015 15:52            46103904
RT-AC87U_378.56_phantom-86499c5.zip                04-Nov-2015 10:31            46108322
RT-AC87U_378.56_phantom-98331e7.zip                05-Oct-2015 16:24            46104413
RT-AC87U_378.56_phantom-9cef9af.zip                02-Nov-2015 11:10            46108312
RT-AC87U_378.56_phantom-ab442fd.zip                01-Sep-2015 15:50            46223138
RT-AC87U_378.56_phantom-c4d20c0.zip                29-Oct-2015 12:54            46108293
RT-AC87U_378.56_phantom-ecc70b1.zip                09-Oct-2015 10:58            46103075
RT-AC87U_378.56_phantom-ed2ed07.zip                28-Oct-2015 10:15            46107220
RT-AC87U_378.56_phantom-eef5d91.zip                09-Sep-2015 12:46            46223464
RT-AC87U_378.56_phantom-fa469e2.zip                10-Sep-2015 11:58            46223778
RT-AC87U_378.57_phantom-3dfecb0.zip                09-Nov-2015 12:10            46110928
RT-AC87U_378.57_phantom-fb3331c.zip                06-Nov-2015 12:18            46110846

**Comment by tuapuikia** [comment]
Hi,

The build is on demand. I already send the command to build ac66U. Please check.

**Comment by tirthob** [comment]
Thank you resolved

**Comment by tirthob** [comment]
Thank you! 

```
 On Thursday, November 12, 2015 10:18 PM, tuapuikia <notifications@github.com> wrote:
```

 Hi,The build is on demand. I already send the command to build ac66U. Please check.—

**Comment by tirthob** [comment]
Hi again please build    
- RT-AC66U 
  I am not able to see it for download here also  which is latest stable build for RT-87U its not clear which is stable build just differnt dates for revision history
  Please advise thanks
  Index of /firmware/

|
|

Index of /firmware/
   |  |

  |

```
On Thursday, November 12, 2015 10:18 PM, tuapuikia <notifications@github.com> wrote:
```

 Hi,The build is on demand. I already send the command to build ac66U. Please check.—
