### ISSUE TITLE
Asus RT-3200 build

### ISSUE THREAD

**Issue by MayurSoneji** [tuapuikia/asuswrt-phantom#6]
Hi, are you able to release the RT-3200 build? I need it for scrambling the VPN. I see the 87u is the only firmware built, is there something in terms of instructions that I'm missing which allows you to compile the build?

**Comment by MayurSoneji** [comment]
I have already got the latest merlin

**Comment by tuapuikia** [comment]
Ok, I will include RT-3200 into my pipeline. Will update here once it ready.

**Comment by MayurSoneji** [comment]
Thanks, Highly appreciated :)

**Comment by MayurSoneji** [comment]
Morning, not to rush you but I have seen the alpha release on the website, do you have a rough idea of completion :)?

**Comment by tuapuikia** [comment]
Hi,

Newer firmware will be based on new code base from Merlin.  I just finish the backport from asuswrt-phantom branch to new branch. It should be ready today or tomorrow for RT-3200 router.

https://github.com/tuapuikia/asuswrt-merlin.ng

**Comment by MayurSoneji** [comment]
Thanks for the update :)

**Comment by tuapuikia** [comment]
Latest firmware with xor patch are now available at https://asuswrt.over9000.wtf/firmware
